'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Vending_Machine.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ButtonBeep() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ButtonBeep", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Coke_Vend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coke_Vend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Credit_Card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Credit_Card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Half_Card_Reader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Half_Card_Reader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key_Pad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key_Pad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Neg_Stickmon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Neg_Stickmon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Neg_Stickmon_run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Neg_Stickmon_run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sold_Out_Light_OFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sold_Out_Light_OFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sold_Out_Light_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sold_Out_Light_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Can_Drinks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Can_Drinks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Coke() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Coke", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Generic_Soda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Generic_Soda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Ice_Cream() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Ice_Cream", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Live_Bait() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Live_Bait", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Mics_Snacks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Mics_Snacks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Mountain_Dew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Mountain_Dew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Pasta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Pasta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Pepsi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Pepsi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Pizza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Pizza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Snacks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Snacks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Snacks_Drinks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Snacks_Drinks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_Forklift_Umbrella() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_Forklift_Umbrella", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stickmon_run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stickmon_run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stickmon_stand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stickmon_stand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stickmon_stand_facing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stickmon_stand_facing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stickmon_Thumbs_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stickmon_Thumbs_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Can_Drinks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Can_Drinks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Generic_Soda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Generic_Soda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Ice_Cream() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Ice_Cream", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Live_Bait() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Live_Bait", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Machine_Mid_Bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Machine_Mid_Bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Machine_white_Door() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Machine_white_Door", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Mics_Snacks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Mics_Snacks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Mountain_Dew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Mountain_Dew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Pasta_Machine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Pasta_Machine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Pizza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Pizza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Snack_Drinks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Snack_Drinks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Snacks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Snacks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vend_Umbrella_Machine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vend_Umbrella_Machine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vending_Machine_Bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vending_Machine_Bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vending_machines_798148() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vending_machines_798148", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vending_machines_Keypad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vending_machines_Keypad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vending_machines_KeypadR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vending_machines_KeypadR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
